"""track users current aquarium

Revision ID: 3a99fa002eb0
Revises: fb0ddf27976a
Create Date: 2019-01-20 10:15:29.306104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a99fa002eb0'
down_revision = 'fb0ddf27976a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_aquarium', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('current_aquarium')

    # ### end Alembic commands ###
