"""re-init

Revision ID: 78d1914f6ffa
Revises: 
Create Date: 2019-01-25 12:19:29.444078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d1914f6ffa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aquarium',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aquarium'))
    )
    with op.batch_alter_table('aquarium', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aquarium_name'), ['name'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('current_aquarium', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=False)

    op.create_table('feeding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('aquarium_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aquarium_id'], ['aquarium.id'], name=op.f('fk_feeding_aquarium_id_aquarium')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_feeding_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feeding'))
    )
    with op.batch_alter_table('feeding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feeding_timestamp'), ['timestamp'], unique=False)

    op.create_table('temperature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temp', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('aquarium_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aquarium_id'], ['aquarium.id'], name=op.f('fk_temperature_aquarium_id_aquarium')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_temperature'))
    )
    with op.batch_alter_table('temperature', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_temperature_timestamp'), ['timestamp'], unique=False)

    op.create_table('water_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('aquarium_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aquarium_id'], ['aquarium.id'], name=op.f('fk_water_change_aquarium_id_aquarium')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_water_change_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_water_change'))
    )
    with op.batch_alter_table('water_change', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_water_change_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_change', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_water_change_timestamp'))

    op.drop_table('water_change')
    with op.batch_alter_table('temperature', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_temperature_timestamp'))

    op.drop_table('temperature')
    with op.batch_alter_table('feeding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feeding_timestamp'))

    op.drop_table('feeding')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('aquarium', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aquarium_name'))

    op.drop_table('aquarium')
    # ### end Alembic commands ###
