"""Added Aquarium

Revision ID: fb0ddf27976a
Revises: 10791c45acf4
Create Date: 2019-01-20 08:31:10.399026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb0ddf27976a'
down_revision = '10791c45acf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feeding', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aquarium_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_feeding_aquarium_id_aquarium'), 'aquarium', ['aquarium_id'], ['id'])

    with op.batch_alter_table('temperature', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aquarium_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_temperature_aquarium_id_aquarium'), 'aquarium', ['aquarium_id'], ['id'])

    with op.batch_alter_table('water_change', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aquarium_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_water_change_aquarium_id_aquarium'), 'aquarium', ['aquarium_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_change', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_water_change_aquarium_id_aquarium'), type_='foreignkey')
        batch_op.drop_column('aquarium_id')

    with op.batch_alter_table('temperature', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_temperature_aquarium_id_aquarium'), type_='foreignkey')
        batch_op.drop_column('aquarium_id')

    with op.batch_alter_table('feeding', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_feeding_aquarium_id_aquarium'), type_='foreignkey')
        batch_op.drop_column('aquarium_id')

    # ### end Alembic commands ###
